perawi_descriptions = {
    "Abu Hurairah": "Sahabat Nabi ﷺ dari kabilah Daus, dikenal sebagai salah satu perawi hadits terbanyak.",
    "Syu'bah": "Syu'bah bin al-Hajjaj, ulama hadits Basrah dari generasi tabi'ut tabi'in, sering dijuluki Amirul Mu'minin fil Hadits.",
    "Sufyan": "Nama ini ambigu; bisa merujuk ke Sufyan ats-Tsauri atau Sufyan bin Uyainah, keduanya imam besar dalam hadits.",
    "Az Zuhri": "Muhammad bin Muslim bin Syihab az-Zuhri, ulama tabi'in Madinah, ahli hadits dan maghazi/sirah.",
    "Ibnu Abbas": "Abdullah bin Abbas, sahabat Nabi ﷺ, sepupu Nabi, dikenal sebagai ahli tafsir Al-Qur'an.",
    "Ibnu Syihab": "Sama dengan Az-Zuhri; nama lengkapnya Muhammad bin Muslim bin Syihab az-Zuhri.",
    "Nafi'": "Nafi' maula Ibnu Umar, tabi'in Madinah dan murid utama Abdullah bin Umar.",
    "Aisyah": "Aisyah binti Abu Bakar, istri Nabi ﷺ, sahabat, ulama perempuan besar, dan perawi banyak hadits.",
    "Qatadah": "Qatadah bin Di'amah as-Sadusi, ulama Basrah, ahli tafsir dan hadits dari generasi tabi'in.",
    "Malik": "Malik bin Anas, Imam Madinah, ahli fikih dan hadits, penyusun Al-Muwaththa' dan pendiri mazhab Maliki.",
    "Ibnu Umar": "Abdullah bin Umar bin Khattab, sahabat Nabi ﷺ dan salah satu perawi hadits besar.",
    "Al A'masy": "Sulaiman bin Mihran al-A'masy, ulama hadits Kufah dari generasi tabi'in/tabi'ut tabi'in.",
    "Waki'": "Waki' bin al-Jarrah, ulama hadits Kufah dan salah satu guru Imam Ahmad bin Hanbal.",
    "Anas bin Malik": "Sahabat Nabi ﷺ, pelayan Nabi sejak kecil, dan salah satu perawi hadits besar.",
    "Qutaibah": "Qutaibah bin Sa'id, muhaddits besar dari Khurasan, guru banyak penyusun kitab hadits.",
    "Anas": "Sama dengan Anas bin Malik, sahabat Nabi ﷺ dan perawi hadits besar.",
    "Yahya bin Sa'id": "Nama ini bisa merujuk ke Yahya bin Sa'id al-Ansari atau Yahya bin Sa'id al-Qattan; perlu konteks sanad untuk memastikan.",
    "Ma'mar": "Ma'mar bin Rasyid, ulama hadits Yaman/Bashrah dari generasi tabi'ut tabi'in, salah satu murid Az-Zuhri.",
    "Yahya": "Nama ini ambigu; bisa merujuk ke beberapa perawi seperti Yahya bin Sa'id al-Qattan, Yahya bin Sa'id al-Ansari, atau Yahya bin Ma'in. Perlu konteks sanad untuk memastikan.",
    "'Aisyah": "Aisyah binti Abu Bakar, istri Nabi ﷺ, sahabat, ulama perempuan besar, dan perawi banyak hadits.",
    "Ibnu Juraij": "Abdul Malik bin Abdul Aziz bin Juraij, ulama Makkah dari generasi tabi'ut tabi'in, dikenal sebagai ahli hadits dan fikih.",
    "Abu Bakr bin Abu Syaibah": "Abu Bakr bin Abi Syaibah, muhaddits Kufah, penyusun kitab Al-Mushannaf, dan guru bagi Imam Muslim serta beberapa ahli hadits besar.",
    "Ayyub": "Ayyub as-Sakhtiyani, ulama Basrah dari generasi tabi'in, dikenal kuat dalam hadits dan ibadah.",
    "Yunus": "Nama ini ambigu; sering merujuk ke Yunus bin Yazid al-Aili, murid Az-Zuhri, tetapi perlu konteks sanad untuk memastikan.",
    "Hisyam": "Nama ini ambigu; bisa merujuk ke Hisyam bin Urwah, Hisyam ad-Dastawa'i, atau perawi lain. Perlu konteks sanad untuk memastikan.",
    "Abdullah": "Nama ini sangat ambigu; bisa merujuk ke banyak perawi seperti Abdullah bin Umar, Abdullah bin Abbas, Abdullah bin Mas'ud, dan lainnya. Perlu konteks sanad.",
    "Abu Bakar bin Abu Syaibah": "Sama dengan Abu Bakr bin Abu Syaibah; muhaddits Kufah, penyusun Al-Mushannaf.",
    "Qutaibah bin Sa'id": "Qutaibah bin Sa'id, muhaddits besar dari Khurasan, guru banyak penyusun kitab hadits seperti Bukhari, Muslim, Abu Dawud, Tirmidzi, dan lainnya.",
    "Abu Ishaq": "Nama ini ambigu; sering merujuk ke Abu Ishaq as-Sabi'i, ulama Kufah dari generasi tabi'in, tetapi perlu konteks sanad untuk memastikan.",
    "Musaddad": "Musaddad bin Musarhad, muhaddits Basrah, salah satu guru Imam Bukhari dan Abu Dawud.",
    "Abu Salamah": "Kemungkinan Abu Salamah bin Abdurrahman bin Auf, tabi'in Madinah, ahli fikih dan hadits, tetapi perlu konteks sanad untuk memastikan.",
    "Muhammad bin Ja'far": "Muhammad bin Ja'far al-Hudzali, dikenal dengan julukan Ghundar, muhaddits Basrah dan murid Syu'bah.",
    "Jabir": "Kemungkinan Jabir bin Abdullah al-Ansari, sahabat Nabi ﷺ dan perawi banyak hadits, tetapi perlu konteks sanad untuk memastikan.",
    "Al Laits": "Al-Laits bin Sa'd, imam besar Mesir, ahli fikih dan hadits, sezaman dengan Imam Malik.",
    "Ishaq bin Ibrahim": "Kemungkinan Ishaq bin Ibrahim bin Rahawaih, atau Ishaq bin Rahuyah, imam besar hadits dan fikih, guru Imam Bukhari dan Muslim.",
    "Ibnu Wahb": "Abdullah bin Wahb, ulama Mesir, murid Imam Malik dan Al-Laits bin Sa'd, ahli hadits dan fikih.",
    "Manshur": "Kemungkinan Manshur bin al-Mu'tamir, ulama hadits Kufah dari generasi tabi'in, dikenal tsiqah dan banyak meriwayatkan dari Ibrahim an-Nakha'i.",
    "Ibrahim": "Nama ini ambigu; sering merujuk ke Ibrahim an-Nakha'i, ulama tabi'in Kufah, ahli fikih dan hadits, tetapi perlu konteks sanad untuk memastikan.",
    "Muhammad bin Al Mutsanna": "Muhammad bin al-Mutsanna al-Anazi, muhaddits Basrah, dikenal dengan julukan az-Zaman, salah satu guru Imam Bukhari, Muslim, Abu Dawud, dan Tirmidzi.",
    "Jarir": "Nama ini ambigu; sering merujuk ke Jarir bin Abdul Hamid adh-Dhabbi, muhaddits Kufah/Ray, tetapi perlu konteks sanad untuk memastikan.",
    "Muhammad bin Basysyar": "Muhammad bin Basysyar al-Abdi, muhaddits Basrah, dikenal dengan julukan Bundar, guru banyak penyusun kitab hadits.",
    "Abu Mu'awiyah": "Abu Mu'awiyah Muhammad bin Khazim adh-Dharir, muhaddits Kufah, banyak meriwayatkan dari Al-A'masy.",
    "Zuhair bin Harb": "Zuhair bin Harb an-Nasa'i, muhaddits besar, salah satu guru Imam Muslim dan perawi dalam banyak kitab hadits.",
    "Hammad": "Nama ini ambigu; bisa merujuk ke Hammad bin Salamah atau Hammad bin Zaid. Perlu konteks sanad untuk memastikan.",
    "Jabir bin Abdullah": "Jabir bin Abdullah al-Ansari, sahabat Nabi ﷺ dari Madinah, salah satu perawi hadits besar.",
    "Abdullah bin Umar": "Abdullah bin Umar bin Khattab, sahabat Nabi ﷺ, putra Umar bin Khattab, dikenal sangat mengikuti sunnah dan banyak meriwayatkan hadits.",
    "Al Hasan": "Kemungkinan Al-Hasan al-Bashri, ulama tabi'in Basrah, ahli zuhud, fikih, tafsir, dan hadits, tetapi perlu konteks sanad untuk memastikan.",
    "Isma'il": "Nama ini ambigu; bisa merujuk ke banyak perawi seperti Isma'il bin Abi Khalid, Isma'il bin Ja'far, atau Isma'il bin Ibrahim. Perlu konteks sanad untuk memastikan.",
    "Abu Usamah": "Abu Usamah Hammad bin Usamah al-Kufi, muhaddits Kufah, guru banyak imam hadits.",
    "Abu Kuraib": "Abu Kuraib Muhammad bin al-Ala al-Hamdani, muhaddits Kufah, salah satu guru Imam Muslim, Abu Dawud, Tirmidzi, dan Ibnu Majah.",
    "Yazid bin Harun": "Yazid bin Harun al-Wasithi, imam hadits besar dari Wasith, dikenal kuat hafalannya dan banyak meriwayatkan hadits.",
    "Hammad bin Salamah": "Hammad bin Salamah bin Dinar, ulama hadits Basrah, guru banyak perawi besar dan dikenal meriwayatkan dari Tsabit al-Bunani serta Qatadah.",
    "Yahya bin Yahya": "Kemungkinan Yahya bin Yahya at-Tamimi an-Naisaburi, muhaddits Khurasan, salah satu perawi utama Shahih Muslim. Perlu konteks sanad untuk memastikan.",
    "Hammad bin Zaid": "Hammad bin Zaid bin Dirham, ulama hadits Basrah, imam tsiqah dan sezaman dengan Hammad bin Salamah.",
    "Sa'id bin Jubair": "Sa'id bin Jubair, ulama tabi'in Kufah, murid Ibnu Abbas, dikenal sebagai ahli tafsir dan perawi hadits.",
    "Khalid": "Nama ini ambigu; bisa merujuk ke banyak perawi seperti Khalid al-Hadzdza', Khalid bin Mihran, atau lainnya. Perlu konteks sanad untuk memastikan.",
    "Abu Sa'id Al Khudri": "Abu Sa'id al-Khudri, sahabat Nabi ﷺ dari kalangan Anshar, salah satu perawi hadits besar.",
    "Abu Shalih": "Nama ini ambigu; sering merujuk ke Abu Shalih as-Samman, tabi'in Madinah dan perawi dari Abu Hurairah, tetapi perlu konteks sanad untuk memastikan.",
    "Sa'id": "Nama ini ambigu; bisa merujuk ke Sa'id bin Jubair, Sa'id bin al-Musayyab, Sa'id bin Abi 'Arubah, atau lainnya. Perlu konteks sanad untuk memastikan.",
    "Husyaim": "Husyaim bin Basyir, muhaddits besar dari Wasith, banyak meriwayatkan dari perawi Irak.",
    "Muhammad": "Nama ini sangat ambigu; bisa merujuk ke banyak perawi. Perlu konteks sanad untuk memastikan.",
    "Abu Az Zubair": "Abu az-Zubair Muhammad bin Muslim al-Makki, tabi'in Makkah, dikenal banyak meriwayatkan dari Jabir bin Abdullah.",
    "Ali": "Nama ini ambigu; bisa merujuk ke Ali bin Abi Thalib atau perawi lain bernama Ali. Perlu konteks sanad untuk memastikan.",
    "Ikrimah": "Ikrimah maula Ibnu Abbas, tabi'in, murid Ibnu Abbas, dikenal dalam riwayat tafsir dan hadits.",
    "'Urwah": "'Urwah bin az-Zubair, tabi'in Madinah, ahli fikih dan hadits, putra Asma binti Abu Bakar dan keponakan Aisyah.",
    "Abdurrazaq": "Abdurrazaq bin Hammam ash-Shan'ani, muhaddits Yaman, penyusun Al-Mushannaf dan guru Imam Ahmad.",
    "Al A'raj": "Abdurrahman bin Hurmuz al-A'raj, tabi'in Madinah, banyak meriwayatkan dari Abu Hurairah.",
    "Ali bin Muhammad": "Nama ini ambigu; kemungkinan Ali bin Muhammad ath-Thanafisi atau perawi lain. Perlu konteks sanad untuk memastikan.",
    "Mujahid": "Mujahid bin Jabr, ulama tabi'in Makkah, murid Ibnu Abbas, terkenal dalam bidang tafsir.",
    "Yahya bin Abu Katsir": "Yahya bin Abi Katsir, ulama tabi'in/awal tabi'ut tabi'in, ahli hadits dari Yamamah.",
    "Musa bin Isma'il": "Musa bin Isma'il at-Tabudzaki, muhaddits Basrah, salah satu guru Imam Bukhari dan Abu Dawud.",
    "Salim": "Nama ini ambigu; sering merujuk ke Salim bin Abdullah bin Umar, tabi'in Madinah dan putra Abdullah bin Umar, tetapi perlu konteks sanad untuk memastikan.",
    "Abu Hurairah radliallahu 'anhu": "Abu Hurairah, sahabat Nabi ﷺ dari kabilah Daus, dikenal sebagai salah satu perawi hadits terbanyak.",
    "Hammam": "Nama ini ambigu; bisa merujuk ke Hammam bin Munabbih, tabi'in Yaman dan murid Abu Hurairah, atau Hammam bin Yahya. Perlu konteks sanad untuk memastikan.",
    "Hisyam bin 'Urwah": "Hisyam bin 'Urwah bin az-Zubair, ulama hadits Madinah, putra 'Urwah bin az-Zubair, banyak meriwayatkan dari ayahnya.",
    "Tsabit": "Kemungkinan Tsabit al-Bunani, ulama tabi'in Basrah, murid Anas bin Malik dan perawi banyak hadits darinya.",
    "Abu Nu'aim": "Abu Nu'aim al-Fadhl bin Dukain, muhaddits Kufah, guru Imam Bukhari dan banyak ahli hadits besar.",
    "Asy Sya'bi": "Amir bin Syarahil asy-Sya'bi, ulama tabi'in Kufah, ahli fikih, hadits, dan sejarah.",
    "Syu'aib": "Nama ini ambigu; sering merujuk ke Syu'aib bin Abi Hamzah, murid Az-Zuhri, tetapi perlu konteks sanad untuk memastikan.",
    "Ibnu 'Abbas": "Abdullah bin Abbas, sahabat Nabi ﷺ, sepupu Nabi, dikenal sebagai ahli tafsir Al-Qur'an dan perawi banyak hadits.",
    "Zuhair": "Nama ini ambigu; bisa merujuk ke Zuhair bin Mu'awiyah atau Zuhair bin Harb. Perlu konteks sanad untuk memastikan.",
    "Abu 'Awanah": "Abu 'Awanah al-Wadhdhah bin Abdullah al-Yasykuri, muhaddits Basrah/Washith, banyak meriwayatkan dari Qatadah dan perawi Irak.",
    "Laits": "Kemungkinan Al-Laits bin Sa'd, imam besar Mesir, ahli fikih dan hadits, tetapi perlu konteks sanad untuk memastikan.",
    "Al Auza'i": "Abdurrahman bin Amr al-Auza'i, imam besar Syam, ahli fikih dan hadits, pendiri mazhab Auza'i.",
    "Muhammad bin Ishaq": "Muhammad bin Ishaq bin Yasar, ulama sirah dan hadits, dikenal sebagai penyusun riwayat awal Sirah Nabawiyah.",
    "'Ubaidullah": "Nama ini ambigu; sering merujuk ke 'Ubaidullah bin Umar al-'Umari, ulama Madinah dan perawi dari Nafi', tetapi perlu konteks sanad untuk memastikan.",
    "Zaid bin Aslam": "Zaid bin Aslam al-Adawi, tabi'in Madinah, ahli tafsir dan hadits, banyak meriwayatkan dari Ibnu Umar dan ayahnya Aslam.",
    "Muhammad bin Rafi'": "Muhammad bin Rafi' an-Naisaburi, muhaddits Khurasan, salah satu guru Imam Muslim.",
    "Ibnu Numair": "Kemungkinan Abdullah bin Numair al-Hamdani atau Muhammad bin Abdullah bin Numair, keduanya muhaddits Kufah. Perlu konteks sanad untuk memastikan.",
    "Abu Sa'id": "Nama ini ambigu; sering merujuk ke Abu Sa'id al-Khudri, sahabat Nabi ﷺ, tetapi perlu konteks sanad untuk memastikan.",
    "Abu Qilabah": "Abu Qilabah Abdullah bin Zaid al-Jarmi, ulama tabi'in Basrah, ahli hadits dan fikih.",
    "Sufyan bin Uyainah": "Sufyan bin Uyainah, imam besar hadits Makkah, salah satu guru Imam Syafi'i dan Ahmad bin Hanbal.",
    "Humaid": "Kemungkinan Humaid ath-Thawil, ulama Basrah, murid Anas bin Malik dan perawi banyak hadits darinya.",
}